#20 デフォルトのリスト表示件数を10件に変更
cfj-afterpillsearch/search-backend pull request #21
Opened 2023-12-12 13:17 UTC by erikka-22

デフォルトのリスト表示件数を10件に変更しました。

2023-12-12 13:21 UTC, tanimuranaomichi commented on src/app/app.controller.ts
>      // perpageパラメータが不正な場合は、20件を返す。 TODO: Pipeで実装する
コメントのところも20→10に直しちゃっていいかなと思いました
TODOにあるPipeで実装もついでにやってしまってもいいかも…？

2023-12-12 15:47 UTC, osappy commented on src/app/app.controller.ts
>      // perpageパラメータが不正な場合は、20件を返す。 TODO: Pipeで実装する
>コメントのところも20→10に直しちゃっていいかなと思いました

こことかだよね？
https://github.com/cfj-afterpillsearch/search-backend/pull/21/files#diff-fa627cf21acb878ddfdd699c5979a62da69dafc71309797184d9b837f8abc10dL142

>TODOにあるPipeで実装もついでにやってしまってもいいかも…？

所詮4行のためにPipe実装するのもなんだかなぁと思うので、自分はこのままでよいと思います。
でもNestJSのドキュメント読んでPipe実装できそうなら別PRであげてください。

2023-12-12 15:48 UTC, osappy requested changes
コメントの修正をお願いします。

2023-12-16 04:48 UTC, tanimuranaomichi commented on src/app/app.controller.ts
>      // perpageパラメータが不正な場合は、20件を返す。 TODO: Pipeで実装する
ここ含めあと3箇所あります！

2023-12-16 06:49 UTC, tanimuranaomichi approved these changes

2023-12-19 13:06 UTC, osappy approved these changes

2023-12-19 13:07 UTC, merged